#!/usr/bin/env bash
# This script is "invincible" against SIGTERM signals
# Trap SIGTERM and print the message
trap "echo 'I am invincible!!!'" SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
